### PR TITLE
Transition exit time and atomic support on Unity 4

### LINKED ISSUE #1028: [Bug]: AnimatorControllers before Unity 5 cannot be exported correctly
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest alpha-build of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Not Applicable

### Which Unity version did this occur on?

4.6.2p2

### Is the game Mono or IL2Cpp?

Not Applicable

### Describe the issue.

If using 0.1.9.9 version, AnimatorControllers before Unity 5 are exported correctly:
AssetRipper_0199
But if using 0.3.2.0 and newer version, these AnimatorControllers' default states are wrong, and the transitions from "Any State" are not exported:
AssetRipper_0340
And some AnimatorTransitions without conditions show this warning (also print in console) because "Has Exit Time" is false:
warn

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by GZHYBFHHJ**
Fixes #1028

### CODE REVIEW

File: Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs [hunk 1]
```diff
@@ -410,12 +416,13 @@ private static IAnimatorState CreateAnimatorState(ProcessedAssetCollection virtu
 			for (int i = 0; i < Transition.ConditionConstantArray.Count; i++)
 			{
 				ConditionConstant conditionConstant = Transition.ConditionConstantArray[i].Data;
-				if (conditionConstant.ConditionMode != (int)AnimatorConditionMode.ExitTime)
+				if (!Transition.Has_ExitTime() || conditionConstant.ConditionMode != (int)AnimatorConditionMode.ExitTime)
```
Comment (ds5678) [inline Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs:419]: Why would `Transition.Has_ExitTime` have any relevance here?

File: Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs [hunk 2]
```diff
@@ -424,10 +431,11 @@ private static IAnimatorState CreateAnimatorState(ProcessedAssetCollection virtu
 			animatorStateTransition.Name = TOS[Transition.UserID];
 			animatorStateTransition.IsExit_C1101 = Transition.IsExit();
 
+			animatorStateTransition.Atomic_C1101 = Transition.Atomic;
 			animatorStateTransition.TransitionDuration_C1101 = Transition.TransitionDuration;
 			animatorStateTransition.TransitionOffset_C1101 = Transition.TransitionOffset;
-			animatorStateTransition.ExitTime_C1101 = Transition.GetExitTime();
-			animatorStateTransition.HasExitTime_C1101 = Transition.GetHasExitTime();
+			animatorStateTransition.ExitTime_C1101 = Transition.ExitTime;
+			animatorStateTransition.HasExitTime_C1101 = Transition.HasExitTime;
```
Comment (ds5678) [inline Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs:438]: Why is this being changed?

**Review by ds5678 — CHANGES_REQUESTED** [review]

File: Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs (hunk 1 above)
Comment (GZHYBFHHJ) [reply Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs:419]: The `ExitTime` of transitions on Unity 4 is stored as a condition.
`Transition.Has_ExitTime` is the same as `generatedStateMachine.Has_ChildStates_C1107()` above, and is used to detect whether this transition is in Unity 5+ format.
However, in transitions on Unity 5+, conditions will not contain ExitTime conditions, so this condition mode judgment can be removed.

Comment (ds5678) [reply Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs:419]: > `Transition.Has_ExitTime` is the same as `generatedStateMachine.Has_ChildStates_C1107()`

They are not the same. They are from two different assets, which could have different Unity versions. `Transition` is from an `IAnimatorController` asset. You should use `!animatorStateTransition.Has_ExitTime_C1101()`.

File: Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs (hunk 2 above)
Comment (ds5678) [reply Source/AssetRipper.Processing/AnimatorControllers/VirtualAnimationFactory.cs:438]: If the `IAnimatorController` and `IAnimatorStateTransition` have the same unity version (which they normally would), this should have no effect, which means you didn't need to change it. Please change it back so that the code can handle a unity version disparity.
